# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     app: payments
#   name: payments
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: payments
#   template:
#     metadata:
#       labels:
#         app: payments
#     spec:
#       containers:
#       - name: payments
#         image: europe-southwest1-docker.pkg.dev/genuine-compass-429914-t4/payments-1/production
#         ports:
#         - containerPort: 3001
#         env:
#         - name: PORT
#           value: '3001'
#         - name: NOTIFY_HOST
#           value: notifications
#         - name: NOTIFY_PORT
#           value: '3000'
#         - name: STRIPE_SECRET_KEY
#           valueFrom:
#             secretKeyRef:
#               name: stripe
#               key: stripeSecretKey



#v2

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payments
  name: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - image: europe-southwest1-docker.pkg.dev/genuine-compass-429914-t4/payments-1/production
          name: payments
          env:
            - name: PORT
              value: '3001'
            - name: NOTIFY_HOST
              value: notifications
            - name: NOTIFY_PORT
              value: '3000'
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe
                  key: stripeSecretKey
