
services:
  e2e:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    depends_on:
      - reservations
      - auth
      - payments
      - notifications
      - mongo
  reservations:
    image:  europe-southwest1-docker.pkg.dev/genuine-compass-429914-t4/reservations-1/production

    env_file:
      - ../apps/reservations/.env
    ports:
      - '3000:3000'
  auth:
    image: europe-southwest1-docker.pkg.dev/genuine-compass-429914-t4/auth-1/production
    env_file:
      - ../apps/auth/.env
    ports:
      - '3001:3001'
  payments:
    image: europe-southwest1-docker.pkg.dev/genuine-compass-429914-t4/payments-1/production
    ports:
      - '3003:3003'
    env_file:
      - ../apps/payments/.env
  notifications:
    image: europe-southwest1-docker.pkg.dev/genuine-compass-429914-t4/notifications-1/production
    ports:
      - '3004:3004'
    env_file:
      - ../apps/notifications/.env
  mongo:
    image: mongo